print("Title : our family")
family1 = str (input("What is your name ? "))
age1 = int (input("How old are you, " + family1 + "? "))
family2 = str (input("What is your name ? "))
age2 = int (input("How old are you, " + family2 + "? "))
family3 = str (input("What is your name ? "))
age3 = int (input("How old are you, " + family3 + "? "))
family4 = str (input("What is your name ? "))
age4 = int (input("How old are you, " + family4 + "? "))
